blank_issues_enabled: false
contact_links:
  - name: MIST Documentation
    url: https://github.com/yourusername/mist/blob/main/README.md
    about: Check the documentation for answers to common questions
  - name: Troubleshooting Guide
    url: https://github.com/yourusername/mist/blob/main/config_docs/troubleshooting_guide.md
    about: Our troubleshooting guide may already have a solution to your problem