---
name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        Please provide as much detail as possible to help us understand your idea.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please check these items before submitting a feature request
      options:
        - label: I have checked the [documentation](https://github.com/yourusername/mist/blob/main/README.md) and confirmed this feature doesn't already exist
          required: true
        - label: I have searched existing issues to make sure this is not a duplicate feature request
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Feature Category
      description: Which part of MIST would this feature enhance?
      options:
        - Notes Management
        - Gmail Integration
        - Calendar Integration
        - Tasks Integration
        - MCP Server Core
        - Google Authentication
        - AI Assistant Integration
        - Documentation
        - Developer Experience
        - User Experience
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Or what need does it address?
      placeholder: When using MIST, I find it difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like MIST to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've also thought about...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have any ideas on how this could be implemented, please share them
      placeholder: This could be implemented by...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, examples, mock-ups, or references that could help us understand the feature request
